DROP VIEW IF EXISTS v_od_AcademicInstitution;

CREATE OR REPLACE VIEW v_od_AcademicInstitution  AS 
SELECT
t.$1  AS InstitutionIdentifier,
t.$2  AS InstitutionName,
t.$3  AS InstitutionNameAlias,
t.$4  AS StreetAddress,
t.$5  AS City,
t.$6  AS State,
t.$7  AS ZipCode,
t.$8  AS StateCode,
t.$9  AS EconomicAnalysisRegions,
t.$10 AS ChiefAdministrator,
t.$11 AS ChiefAdministratorTitle,
t.$12 AS TelephoneNumber,
t.$13 AS EmployerIdentificationNumber,
t.$14 AS DunBradstreetNumbers,
t.$15 AS PostsecondaryEducationIDNumber,
t.$16 AS TitleIVEligibilityIndicatorCode,
t.$17 AS InstitutionsWebAddress,
t.$18 AS AdmissionsOfficeWebAddress,
t.$19 AS FinancialAidOfficeWebAddress,
t.$20 AS OnlineApplicationWebAddress,
t.$21 AS NetPriceCalculatorWebAddress,
t.$22 AS VeteransMilitaryServiceTuitionPoliciesWebAddress,
t.$23 AS StudentRightAthleteGraduationRateWebAddress,
t.$24 AS DisabilityServicesWebAddress,
t.$25 AS SectorOfInstitution,
t.$26 AS LevelOfInstitution,
t.$27 AS ControlOfInstitution,
t.$28 AS HighestLevelOfOffering,
t.$29 AS UndergraduateOffering,
t.$30 AS GraduateOffering,
t.$31 AS HighestDegreeOffered,
t.$32 AS DegreeGrantingStatus,
t.$33 AS HistoricallyBlackCollegeOrUniversity,
t.$34 AS InstitutionHasHospital,
t.$35 AS InstitutionGrantsMedicalDegree,
t.$36 AS TribalCollege,
t.$37 AS DegreeOfUrbanization,
t.$38 AS InstitutionOpenToGeneralPublic,
t.$39 AS StatusOfInstitution,
t.$40 AS UnitidForMergedSchools,
t.$41 AS YearInstitutionWasDeletedFromIPEDS,
t.$42 AS DateInstitutionClosed,
t.$43 AS InstitutionIsActive,
t.$44 AS PrimarilyPostsecondaryIndicator,
t.$45 AS PostsecondaryInstitutionIndicator,
t.$46 AS PostsecondaryAndTitleIvInstitutionIndicator,
t.$47 AS ReportingMethodForStudentCharges,
t.$48 AS InstitutionalCategory,
t.$49 AS CarnegieClassification2015Basic,
t.$50 AS CarnegieClassification2015UndergraduateProgram,
t.$51 AS CarnegieClassification2015GraduateProgram,
t.$52 AS CarnegieClassification2015UndergraduateProfile,
t.$53 AS CarnegieClassification2015EnrollmentProfile,
t.$54 AS CarnegieClassification2015SizeSetting,
t.$55 AS CarnegieClassification20052010Basic,
t.$56 AS CarnegieClassification2000,
t.$57 AS LandGrantInstitution,
t.$58 AS InstitutionSizeCategory,
t.$59 AS MultiCampusOrganization,
t.$60 AS NameOfMultiCampusOrganization,
t.$61 AS IdentificationNumberOfMultiCampusOrganization,
t.$62 AS CoreBasedStatisticalArea,
t.$63 AS CBSATypeMetropolitanMicropolitan,
t.$64 AS CombinedStatisticalArea,
t.$65 AS NewEnglandCityAndTownArea,
t.$66 AS FIPSCountyCode,
t.$67 AS CountyName,
t.$68 AS StateAnd114thCongressionalDistrictID,
t.$69 AS LongitudeLocation,
t.$70 AS LatitudeLocation,
t.$71 AS NCESGroupCategory,
t.$72 AS DataFeedbackReport,
CAST(substring(metadata$filename, 3, 4) AS INTEGER) 
			AcademicYear,
metadata$filename IngestedFileName,
metadata$file_row_number-1 RowNumber 
FROM
   @IPEDS_HD t 
WHERE
   metadata$file_row_number > 1;
