CALL pr_InstitutionalCharge_Load(2017::FLOAT);
CALL pr_InstitutionalCharge_Load(2018::FLOAT);
CALL pr_InstitutionalCharge_Load(2019::FLOAT);

CALL pr_InstitutionalChargeByAcademicBranch_Load(2017::FLOAT);
CALL pr_InstitutionalChargeByAcademicBranch_Load(2018::FLOAT);
CALL pr_InstitutionalChargeByAcademicBranch_Load(2019::FLOAT);

CALL pr_InstitutionalChargeByResidencyType_Load(2017::FLOAT);
CALL pr_InstitutionalChargeByResidencyType_Load(2018::FLOAT);
CALL pr_InstitutionalChargeByResidencyType_Load(2019::FLOAT);

CALL pr_InstitutionalChargeByCategory_Load(2017::FLOAT);
CALL pr_InstitutionalChargeByCategory_Load(2018::FLOAT);
CALL pr_InstitutionalChargeByCategory_Load(2019::FLOAT);
